"use client";

import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
    en: {
        dashboard: "Dashboard",
        home: "Home",
        romGenerator: "ROM Generator",
        createNew: "Create New",
        searchRom: "Search ROM",
        myRoms: "My ROM's",
        approvals: "Approvals",
        romProposalApprovals: "ROM Proposal Approvals",
        coveragePlot: "Coverage Plot",
        settings: "Settings",
        systemUser: "System User",
        systemSettings: "System Settings",
        logout: "Logout",
        profile: "Profile",
        welcome: "Welcome to SalesHub 2.0",
        selectOption: "Select an option from the sidebar to get started.",
        // Form Common
        back: "Back",
        next: "Next",
        create: "Create",
        createNewRom: "Create New ROM",
        enterVenueAddressBelow: "Enter the venue address below to start creating your ROM.",
        yes: "YES",
        no: "NO",
        loadingMap: "Loading Map...",
        osmView: "OpenStreetMap View",
        // Venue Info
        venueInfo: "Venue Information",
        venueName: "Venue Name",
        venueNamePlaceholder: "Type the venue name",
        venueAddress: "Venue Address",
        venueAddressPlaceholder: "Type the venue full address",
        venueType: "Venue Type",
        venueTypePlaceholder: "Select the venue type",
        stadium: "Stadium",
        arena: "Arena",
        conventionCenter: "Convention Center",
        officeBuilding: "Office Building",
        numFloors: "Number of Floors",
        numFloorsPlaceholder: "Type the total number of floors",
        grossSqFt: "Gross sq. ft. (Total)",
        grossSqFtPlaceholder: "Type the total gross sq. ft.",
        parkingGarage: "Parking Garage",
        parkingSqFt: "Parking Garage sq. ft.",
        parkingSqFtPlaceholder: "Type the total number parking sq. ft.",
        pops: "Populations Covered (PoPs)",
        popsPlaceholder: "Type the total number of pops",
        thirdParty: "3rd Party",
        thirdPartyName: "3rd Party Name",
        thirdPartyNamePlaceholder: "Type the 3rd party name",
        thirdPartyFee: "3rd Partner Fee (%)",
        thirdPartyFeePlaceholder: "Enter the 3rd partner fee",
        ahjRequirements: "AHJ Requirements",
        buildingDensity: "Building Density",
        densityPlaceholder: "Select the density",
        low: "Low",
        medium: "Medium",
        high: "High",
        salesManager: "Sales Manager",
        salesManagerPlaceholder: "Type the sales manager/account owner",
        expectedCloseDate: "Expected Close Date",
        expectedConstructionStart: "Expected Construction Start Date",
        expectedOnAirDate: "Expected On Air Date",
        // System Info
        systemInfo: "System Information",
        systemType: "System Type",
        systemTypePlaceholder: "Select the type of the system",
        dasArchitecture: "DAS Architecture",
        architecturePlaceholder: "Select architecture",
        active: "Active",
        passive: "Passive",
        hybrid: "Hybrid",
        oemCriteria: "OEM Selection Criteria",
        oemCriteriaPlaceholder: "OEM Selection Criteria",
        performance: "Performance",
        cost: "Cost",
        legacySupport: "Legacy Support",
        dasVendor: "DAS Vendor",
        dasVendorPlaceholder: "Select DAS Vendor",
        bdaVendor: "BDA/Booster Vendor",
        bdaVendorPlaceholder: "Select BDA Vendor",
        coverageArea: "ERCES Coverage Area",
        coverageAreaPlaceholder: "Select Coverage Area",
        fullBuilding: "Full Building",
        criticalAreas: "Critical Areas Only",
        sectorCriteria: "# of Sectors Criteria",
        sectorCriteriaPlaceholder: "Select the criteria",
        capacity: "Capacity",
        coverage: "Coverage",
        numSectors: "Number of Sectors",
        signalSource: "Signal Source per Carrier",
        signalSourcePlaceholder: "Select signal source",
        offAir: "Off-Air",
        bts: "Base Transceiver Station",
        smallCell: "Small Cell",
        carrierRequirements: "Carrier Requirements",
        techSupported: "Technology Supported",
        additionalInfo: "Additional Information",
        additionalInfoPlaceholder: "Enter any additional details, notes, or requirements here...",
        // Coverage Plot Form
        createCoveragePlot: "Create New Coverage Plot",
        enterAddressBelow: "Enter the address below to start creating your new coverage plot.",
        coverageTypeLabel: "Coverage type",
        indoor: "Indoor",
        outdoor: "Outdoor",
        indoorOutdoor: "Indoor & Outdoor",
        success: "Success!",
        snapshotsDownloaded: "Snapshots of coverage plot for",
        hasBeenDownloaded: "has been downloaded",
        creating: "Creating...",
        close: "Close",
        createCoveragePlotButton: "Create Coverage Plot",
        venueAddressRequired: "Venue Address",
        carrierRequirementsRequired: "Carrier Requirements",
        coverageTypeRequired: "Coverage Type",
        // User Management
        systemUsers: "System Users",
        addUser: "Add User",
        addNewUser: "Add New User",
        createUserDesc: "Create a new user account. They will receive an email to set their password.",
        name: "Name",
        email: "Email",
        role: "Role",
        selectRole: "Select a role",
        userRole: "User",
        adminRole: "Admin",
        superAdminRole: "Super Admin",
        createUser: "Create User",
        joined: "Joined",
        actions: "Actions",
        noUsersFound: "No users found.",
        totalUsers: "Total Users",
        // Coverage Plots
        allPlots: "All Plots",
        myPlots: "My Plots",
        viewPlot: "View Plot",
        plotDetails: "Plot Details",
        userName: "User Name",
        carriers: "Carriers",
        coverageTypes: "Coverage Types",
        noPlotsFound: "No plots found.",
        // System Settings Page
        currentLanguageLabel: "Current Language",
        themeTab: "Theme",
        languageTab: "Language",
        highContrastTab: "High Contrast Mode",
        brightMode: "Bright Mode",
        darkModeLabel: "Dark Mode",
        themeDescription: "Switch between light and dark appearance",
        languageDescription: "Choose your preferred language",
        highContrastDescription: "Increase contrast for better visibility",
        accountInfo: "Account Information",
        english: "English",
        spanish: "Spanish",
        portuguese: "Portuguese",
        french: "French",
        // Dashboard
        leadConversionRate: "Lead Conversion Rate",
        romToProposalRate: "ROM to Proposal Rate",
        onGoingDeals: "On-going Deals",
        romsRequested: "ROMs Requested",
        thisYear: "This Year",
        lastYear: "Last Year",
        last6Months: "Last 6 Months",
        last3Months: "Last 3 Months",
        download: "Download",
        latestRomRequested: "Latest ROM Requested",
        propertyName: "Property Name",
        areaSqFt: "Area (sq. ft.)",
        frequency: "Frequency",
        solution: "Solution",
        lastUpdate: "Last Update",
        status: "Status",
        localConnectivity: "Local Connectivity",
        lost: "LOST",
        won: "WON",
        onGoing: "On-going",
        // All ROMs / ROM Table
        romProposalsTitle: "ROM Proposals",
        searchAndViewRomProposals: "Search and view all generated ROM proposals",
        errorLoadingRomProposals: "Error loading ROM proposals",
        noRomProposalsFound: "No ROM proposals found",
        searchByVenueNameAddress: "Search by venue name, address, type, vendor...",
        sortByVenueName: "Sort by Venue Name",
        noSorting: "No Sorting",
        venueNameAZ: "Venue Name: A → Z",
        venueNameZA: "Venue Name: Z → A",
        typeColumn: "Type",
        floors: "Floors",
        venueAddress: "Venue Address",
        totalCoverageAreaSqFt: "Total Coverage Area (sq ft)",
        parking: "Parking",
        systemType: "System Type",
        vendor: "Vendor",
        sectors: "Sectors",
        action: "Action",
        confirmDeleteRom: "Delete ROM Proposal?",
        confirmDeleteRomDesc: "This will permanently delete this ROM proposal and its files. This action cannot be undone.",
        deleteButton: "Delete",
        romProposalDeleted: "ROM proposal deleted",
        failedToDeleteRom: "Failed to Delete ROM Proposal",
        rowsPerPage: "Rows per page",
        page: "Page",
        of: "of",
        previous: "Previous",
        next: "Next",
        first: "First",
        last: "Last",
        // View ROM Proposals / Approvals
        romProposalsAwaitingApproval: "ROM proposals awaiting your approval",
        pendingProposal: "Pending Proposal",
        pendingProposals: "Pending Proposals",
        searchByVenueAddressCreator: "Search by venue, address, or creator...",
        noPendingMatch: "No pending proposals match your search",
        noPendingProposals: "No pending ROM proposals",
        allProposalsReviewed: "All proposals have been reviewed",
        reject: "Reject",
        approve: "Approve",
        approveRomProposalTitle: "Approve ROM Proposal?",
        rejectRomProposalTitle: "Reject ROM Proposal?",
        approveRomProposalConfirm: "Are you sure you want to approve the ROM proposal? This will mark it as an accepted proposal.",
        rejectRomProposalConfirm: "Are you sure you want to reject the ROM proposal? The creator will see this proposal as rejected.",
        cancel: "Cancel",
        approved: "Approved",
        rejected: "Rejected",
        pending: "Pending",
        proposalApprovedSuccess: "ROM proposal approved successfully",
        proposalRejectedSuccess: "ROM proposal rejected",
        approvedRoms: "Approved ROMs",
        allAcceptedProposals: "All accepted ROM proposals across the platform",
        yourAcceptedProposals: "Your ROM proposals that have been accepted",
        searchByVenueAddressOrCreator: "Search by venue, address, or creator...",
        searchByVenueAddressOrSystem: "Search by venue, address, or system...",
        noApprovedMatch: "No approved proposals match your search",
        noApprovedProposalsYet: "No approved ROM proposals yet",
        errorLoadingApprovedRoms: "Error loading approved ROMs",
        // Coverage Plots
        coveragePlotsHeader: "Coverage Plots",
        viewAllCoveragePlots: "View all coverage plots from all users",
        errorLoadingPlots: "Error loading plots",
        coveragePlotDeleted: "Coverage plot deleted",
        failedToDeletePlot: "Failed to delete plot",
        pleaseFillMandatoryFields: "Please fill in all mandatory fields.",
        mandatoryFieldsDescription: "Venue Address, Carrier Requirements, and Coverage Type are required.",
        unknownUser: "Unknown User",
        // Process Queue
        processQueue: "Process Queue",
        processQueueSubtitle: "Current status of all automation processes",
        automationQueue: "Automation Queue",
        activeProcess: "active process",
        activeProcesses: "active processes",
        loadingQueue: "Loading queue...",
        noActiveProcesses: "No active automation processes.",
        queueEmpty: "The queue is currently empty.",
        processing: "Processing",
        running: "Running",
        waiting: "Waiting...",
        waitingFilesLabel: "Waiting files: ",
        searchByUsernameOrAddress: "Search by username or venue address...",
        sortByAddress: "Sort by Address",
        addressAZ: "Address: A → Z",
        addressZA: "Address: Z → A",
    },
    es: {
        dashboard: "Tablero",
        home: "Inicio",
        romGenerator: "Generador ROM",
        createNew: "Crear Nuevo",
        searchRom: "Buscar ROM",
        myRoms: "Mis ROMs",
        approvals: "Aprobaciones",
        romProposalApprovals: "Aprobaciones de Propuestas ROM",
        coveragePlot: "Gráfico de Cobertura",
        settings: "Configuración",
        systemUser: "Usuario del Sistema",
        systemSettings: "Configuración del Sistema",
        logout: "Cerrar Sesión",
        profile: "Perfil",
        welcome: "Bienvenido a SalesHub 2.0",
        selectOption: "Seleccione una opción de la barra lateral para comenzar.",
        // Form Common
        back: "Atrás",
        next: "Siguiente",
        create: "Crear",
        createNewRom: "Crear Nuevo ROM",
        enterVenueAddressBelow: "Ingrese la dirección del lugar a continuación para comenzar a crear su ROM.",
        yes: "SÍ",
        no: "NO",
        loadingMap: "Cargando Mapa...",
        osmView: "Vista OpenStreetMap",
        // Venue Info
        venueInfo: "Información del Lugar",
        venueName: "Nombre del Lugar",
        venueNamePlaceholder: "Escriba el nombre del lugar",
        venueAddress: "Dirección del Lugar",
        venueAddressPlaceholder: "Escriba la dirección completa",
        venueType: "Tipo de Lugar",
        venueTypePlaceholder: "Seleccione el tipo de lugar",
        stadium: "Estadio",
        arena: "Arena",
        conventionCenter: "Centro de Convenciones",
        officeBuilding: "Edificio de Oficinas",
        numFloors: "Número de Pisos",
        numFloorsPlaceholder: "Escriba el número total de pisos",
        grossSqFt: "Pies Cuadrados Brutos (Total)",
        grossSqFtPlaceholder: "Escriba el total de pies cuadrados brutos",
        parkingGarage: "Garaje de Estacionamiento",
        parkingSqFt: "Pies Cuadrados del Garaje",
        parkingSqFtPlaceholder: "Escriba el total de pies cuadrados del garaje",
        pops: "Poblaciones Cubiertas (PoPs)",
        popsPlaceholder: "Escriba el número total de pops",
        thirdParty: "Tercero",
        thirdPartyName: "Nombre del Tercero",
        thirdPartyNamePlaceholder: "Escriba el nombre del tercero",
        thirdPartyFee: "Tarifa del Tercero (%)",
        thirdPartyFeePlaceholder: "Ingrese la tarifa del tercero",
        ahjRequirements: "Requisitos AHJ",
        buildingDensity: "Densidad del Edificio",
        densityPlaceholder: "Seleccione la densidad",
        low: "Baja",
        medium: "Media",
        high: "Alta",
        salesManager: "Gerente de Ventas",
        salesManagerPlaceholder: "Escriba el gerente de ventas/propietario de la cuenta",
        expectedCloseDate: "Fecha de Cierre Esperada",
        expectedConstructionStart: "Fecha de Inicio de Construcción Esperada",
        expectedOnAirDate: "Fecha de Emisión Esperada",
        // System Info
        systemInfo: "Información del Sistema",
        systemType: "Tipo de Sistema",
        systemTypePlaceholder: "Seleccione el tipo de sistema",
        dasArchitecture: "Arquitectura DAS",
        architecturePlaceholder: "Seleccione arquitectura",
        active: "Activa",
        passive: "Pasiva",
        hybrid: "Híbrida",
        oemCriteria: "Criterios de Selección OEM",
        oemCriteriaPlaceholder: "Criterios de Selección OEM",
        performance: "Rendimiento",
        cost: "Costo",
        legacySupport: "Soporte Legado",
        dasVendor: "Proveedor DAS",
        dasVendorPlaceholder: "Seleccione Proveedor DAS",
        bdaVendor: "Proveedor BDA/Booster",
        bdaVendorPlaceholder: "Seleccione Proveedor BDA",
        coverageArea: "Área de Cobertura ERCES",
        coverageAreaPlaceholder: "Seleccione Área de Cobertura",
        fullBuilding: "Edifício Completo",
        criticalAreas: "Solo Áreas Críticas",
        sectorCriteria: "Criterios de # de Sectores",
        sectorCriteriaPlaceholder: "Seleccione los criterios",
        capacity: "Capacidad",
        coverage: "Cobertura",
        numSectors: "Número de Sectores",
        signalSource: "Fuente de Señal por Operador",
        signalSourcePlaceholder: "Seleccione fuente de señal",
        offAir: "Off-Air",
        bts: "Estación Base Transceptora",
        smallCell: "Celda Pequeña",
        carrierRequirements: "Requisitos del Operador",
        techSupported: "Tecnología Soportada",
        additionalInfo: "Información Adicional",
        additionalInfoPlaceholder: "Ingrese detalles adicionales, notas o requisitos aquí...",
        // Coverage Plot Form
        createCoveragePlot: "Crear Nuevo Gráfico de Cobertura",
        enterAddressBelow: "Ingrese la dirección a continuación para comenzar.",
        coverageTypeLabel: "Tipo de Cobertura",
        indoor: "Interior",
        outdoor: "Exterior",
        indoorOutdoor: "Interior y Exterior",
        success: "¡Éxito!",
        snapshotsDownloaded: "Las instantáneas del gráfico de cobertura para",
        hasBeenDownloaded: "se han descargado",
        creating: "Creando...",
        close: "Cerrar",
        createCoveragePlotButton: "Crear Gráfico de Cobertura",
        venueAddressRequired: "Dirección del Lugar",
        carrierRequirementsRequired: "Requisitos del Operador",
        coverageTypeRequired: "Tipo de Cobertura",
        // User Management
        systemUsers: "Usuarios del Sistema",
        addUser: "Agregar Usuario",
        addNewUser: "Agregar Nuevo Usuario",
        createUserDesc: "Crear una nueva cuenta de usuario. Recibirán un correo electrónico para establecer su contraseña.",
        name: "Nombre",
        email: "Correo Electrónico",
        role: "Rol",
        selectRole: "Seleccionar un rol",
        userRole: "Usuario",
        adminRole: "Administrador",
        superAdminRole: "Super Administrador",
        createUser: "Crear Usuario",
        joined: "Unido",
        actions: "Acciones",
        noUsersFound: "No se encontraron usuarios.",
        totalUsers: "Usuarios Totales",
        // Coverage Plots
        allPlots: "Todos los Gráficos",
        myPlots: "Mis Gráficos",
        viewPlot: "Ver Gráfico",
        plotDetails: "Detalles del Gráfico",
        userName: "Nombre de Usuario",
        carriers: "Operadores",
        coverageTypes: "Tipos de Cobertura",
        noPlotsFound: "No se encontraron gráficos.",
        // System Settings Page
        currentLanguageLabel: "Idioma Actual",
        themeTab: "Tema",
        languageTab: "Idioma",
        highContrastTab: "Modo de Alto Contraste",
        brightMode: "Modo Claro",
        darkModeLabel: "Modo Oscuro",
        themeDescription: "Cambia entre apariencia clara y oscura",
        languageDescription: "Elige tu idioma preferido",
        highContrastDescription: "Aumenta el contraste para mejor visibilidad",
        accountInfo: "Información de la Cuenta",
        english: "Inglés",
        spanish: "Español",
        portuguese: "Portugués",
        french: "Francés",
        // Dashboard
        leadConversionRate: "Tasa de Conversión de Leads",
        romToProposalRate: "Tasa ROM a Propuesta",
        onGoingDeals: "Negocios en Curso",
        romsRequested: "ROMs Solicitados",
        thisYear: "Este Año",
        lastYear: "Año Anterior",
        last6Months: "Últimos 6 Meses",
        last3Months: "Últimos 3 Meses",
        download: "Descargar",
        latestRomRequested: "Última ROM Solicitada",
        propertyName: "Nombre de Propiedad",
        areaSqFt: "Área (pies²)",
        frequency: "Frecuencia",
        solution: "Solución",
        lastUpdate: "Última Actualización",
        status: "Estado",
        localConnectivity: "Conectividad Local",
        lost: "PERDIDO",
        won: "GANADO",
        onGoing: "En Curso",
        romProposalsTitle: "Propuestas ROM",
        searchAndViewRomProposals: "Buscar y ver todas las propuestas ROM generadas",
        errorLoadingRomProposals: "Error al cargar propuestas ROM",
        noRomProposalsFound: "No se encontraron propuestas ROM",
        searchByVenueNameAddress: "Buscar por nombre, dirección, tipo, proveedor...",
        sortByVenueName: "Ordenar por Nombre del Lugar",
        noSorting: "Sin Ordenar",
        venueNameAZ: "Nombre del Lugar: A → Z",
        venueNameZA: "Nombre del Lugar: Z → A",
        typeColumn: "Tipo",
        venueAddress: "Dirección del Lugar",
        totalCoverageAreaSqFt: "Área Total de Cobertura (pies²)",
        parking: "Estacionamiento",
        systemType: "Tipo de Sistema",
        vendor: "Proveedor",
        sectors: "Sectores",
        action: "Acción",
        confirmDeleteRom: "¿Eliminar Propuesta ROM?",
        confirmDeleteRomDesc: "Esto eliminará permanentemente esta propuesta ROM y sus archivos. Esta acción no se puede deshacer.",
        deleteButton: "Eliminar",
        romProposalDeleted: "Propuesta ROM eliminada",
        failedToDeleteRom: "Error al eliminar propuesta ROM",
        rowsPerPage: "Filas por página",
        page: "Página",
        of: "de",
        previous: "Anterior",
        next: "Siguiente",
        first: "Primera",
        last: "Última",
        romProposalsAwaitingApproval: "Propuestas ROM pendientes de su aprobación",
        pendingProposal: "Propuesta Pendiente",
        pendingProposals: "Propuestas Pendientes",
        searchByVenueAddressCreator: "Buscar por lugar, dirección o creador...",
        noPendingMatch: "Ninguna propuesta pendiente coincide con su búsqueda",
        noPendingProposals: "No hay propuestas ROM pendientes",
        allProposalsReviewed: "Todas las propuestas han sido revisadas",
        reject: "Rechazar",
        approve: "Aprobar",
        approveRomProposalTitle: "¿Aprobar Propuesta ROM?",
        rejectRomProposalTitle: "¿Rechazar Propuesta ROM?",
        approveRomProposalConfirm: "¿Está seguro de que desea aprobar la propuesta ROM? Se marcará como propuesta aceptada.",
        rejectRomProposalConfirm: "¿Está seguro de que desea rechazar la propuesta ROM? El creador verá esta propuesta como rechazada.",
        cancel: "Cancelar",
        approved: "Aprobado",
        rejected: "Rechazado",
        pending: "Pendiente",
        proposalApprovedSuccess: "Propuesta ROM aprobada correctamente",
        proposalRejectedSuccess: "Propuesta ROM rechazada",
        approvedRoms: "ROMs Aprobados",
        allAcceptedProposals: "Todas las propuestas ROM aceptadas en la plataforma",
        yourAcceptedProposals: "Sus propuestas ROM que han sido aceptadas",
        searchByVenueAddressOrCreator: "Buscar por lugar, dirección o creador...",
        searchByVenueAddressOrSystem: "Buscar por lugar, dirección o sistema...",
        noApprovedMatch: "Ninguna propuesta aprobada coincide con su búsqueda",
        noApprovedProposalsYet: "Aún no hay propuestas ROM aprobadas",
        errorLoadingApprovedRoms: "Error al cargar ROMs aprobados",
        coveragePlotsHeader: "Gráficos de Cobertura",
        viewAllCoveragePlots: "Ver todos los gráficos de cobertura de todos los usuarios",
        errorLoadingPlots: "Error al cargar gráficos",
        coveragePlotDeleted: "Gráfico de cobertura eliminado",
        failedToDeletePlot: "Error al eliminar gráfico",
        pleaseFillMandatoryFields: "Por favor complete todos los campos obligatorios.",
        mandatoryFieldsDescription: "Dirección del Lugar, Requisitos de Operadores y Tipo de Cobertura son obligatorios.",
        unknownUser: "Usuario Desconocido",
        processQueue: "Cola de Procesos",
        processQueueSubtitle: "Estado actual de todos los procesos de automatización",
        automationQueue: "Cola de Automatización",
        activeProcess: "proceso activo",
        activeProcesses: "procesos activos",
        loadingQueue: "Cargando cola...",
        noActiveProcesses: "No hay procesos de automatización activos.",
        queueEmpty: "La cola está vacía.",
        processing: "Procesando",
        running: "En ejecución",
        waiting: "Esperando...",
        waitingFilesLabel: "Archivos en espera: ",
        searchByUsernameOrAddress: "Buscar por usuario o dirección del lugar...",
        sortByAddress: "Ordenar por Dirección",
        addressAZ: "Dirección: A → Z",
        addressZA: "Dirección: Z → A",
    },
    pt: {
        dashboard: "Painel",
        home: "Início",
        romGenerator: "Gerador ROM",
        createNew: "Criar Novo",
        searchRom: "Buscar ROM",
        myRoms: "Meus ROMs",
        approvals: "Aprovações",
        romProposalApprovals: "Aprovações de Propostas ROM",
        coveragePlot: "Gráfico de Cobertura",
        settings: "Configurações",
        systemUser: "Usuário do Sistema",
        systemSettings: "Configurações do Sistema",
        logout: "Sair",
        profile: "Perfil",
        welcome: "Bem-vindo ao SalesHub 2.0",
        selectOption: "Selecione uma opção na barra lateral para começar.",
        // Form Common
        back: "Voltar",
        next: "Próximo",
        create: "Criar",
        createNewRom: "Criar Novo ROM",
        enterVenueAddressBelow: "Digite o endereço do local abaixo para começar a criar seu ROM.",
        yes: "SIM",
        no: "NÃO",
        loadingMap: "Carregando Mapa...",
        osmView: "Visualização OpenStreetMap",
        // Venue Info
        venueInfo: "Informações do Local",
        venueName: "Nome do Local",
        venueNamePlaceholder: "Digite o nome do local",
        venueAddress: "Endereço do Local",
        venueAddressPlaceholder: "Digite o endereço completo",
        venueType: "Tipo de Local",
        venueTypePlaceholder: "Selecione o tipo de local",
        stadium: "Estádio",
        arena: "Arena",
        conventionCenter: "Centro de Convenções",
        officeBuilding: "Edifício de Escritórios",
        numFloors: "Número de Andares",
        numFloorsPlaceholder: "Digite o número total de andares",
        grossSqFt: "Área Bruta (Total)",
        grossSqFtPlaceholder: "Digite o total da área bruta",
        parkingGarage: "Garagem",
        parkingSqFt: "Área da Garagem",
        parkingSqFtPlaceholder: "Digite a área total da garagem",
        pops: "Populações Cobertas (PoPs)",
        popsPlaceholder: "Digite o número total de pops",
        thirdParty: "Terceiros",
        thirdPartyName: "Nome do Terceiro",
        thirdPartyNamePlaceholder: "Digite o nome do terceiro",
        thirdPartyFee: "Taxa do Terceiro (%)",
        thirdPartyFeePlaceholder: "Insira a taxa do terceiro",
        ahjRequirements: "Requisitos AHJ",
        buildingDensity: "Densidade do Edifício",
        densityPlaceholder: "Selecione a densidade",
        low: "Baixa",
        medium: "Média",
        high: "Alta",
        salesManager: "Gerente de Vendas",
        salesManagerPlaceholder: "Digite o gerente de vendas/proprietário da conta",
        expectedCloseDate: "Data Prevista de Fechamento",
        expectedConstructionStart: "Data Prevista de Início da Construção",
        expectedOnAirDate: "Data Prevista de Entrada no Ar",
        // System Info
        systemInfo: "Informações do Sistema",
        systemType: "Tipo de Sistema",
        systemTypePlaceholder: "Selecione o tipo de sistema",
        dasArchitecture: "Arquitetura DAS",
        architecturePlaceholder: "Selecione a arquitetura",
        active: "Ativa",
        passive: "Passiva",
        hybrid: "Híbrida",
        oemCriteria: "Critérios de Seleção OEM",
        oemCriteriaPlaceholder: "Critérios de Seleção OEM",
        performance: "Desempenho",
        cost: "Custo",
        legacySupport: "Suporte Legado",
        dasVendor: "Fornecedor DAS",
        dasVendorPlaceholder: "Selecione Fornecedor DAS",
        bdaVendor: "Fornecedor BDA/Booster",
        bdaVendorPlaceholder: "Selecione Fornecedor BDA",
        coverageArea: "Área de Cobertura ERCES",
        coverageAreaPlaceholder: "Selecione Área de Cobertura",
        fullBuilding: "Edifício Completo",
        criticalAreas: "Apenas Áreas Críticas",
        sectorCriteria: "Critérios de # de Setores",
        sectorCriteriaPlaceholder: "Selecione os critérios",
        capacity: "Capacidade",
        coverage: "Cobertura",
        numSectors: "Número de Setores",
        signalSource: "Fonte de Sinal por Operadora",
        signalSourcePlaceholder: "Selecione fonte de sinal",
        offAir: "Off-Air",
        bts: "Estação Transceptora Base",
        smallCell: "Small Cell",
        carrierRequirements: "Requisitos da Operadora",
        techSupported: "Tecnologia Suportada",
        additionalInfo: "Informações Adicionais",
        additionalInfoPlaceholder: "Insira detalhes adicionais, notas ou requisitos aqui...",
        // Coverage Plot Form
        createCoveragePlot: "Criar Novo Gráfico de Cobertura",
        enterAddressBelow: "Insira o endereço abaixo para começar.",
        coverageTypeLabel: "Tipo de Cobertura",
        indoor: "Interior",
        outdoor: "Exterior",
        indoorOutdoor: "Interior e Exterior",
        success: "Sucesso!",
        snapshotsDownloaded: "Instantâneos do gráfico de cobertura para",
        hasBeenDownloaded: "foram baixados",
        creating: "Criando...",
        close: "Fechar",
        createCoveragePlotButton: "Criar Gráfico de Cobertura",
        venueAddressRequired: "Endereço do Local",
        carrierRequirementsRequired: "Requisitos da Operadora",
        coverageTypeRequired: "Tipo de Cobertura",
        // User Management
        systemUsers: "Usuários do Sistema",
        addUser: "Adicionar Usuário",
        addNewUser: "Adicionar Novo Usuário",
        createUserDesc: "Crie uma nova conta de usuário. Eles receberão um e-mail para definir a senha.",
        name: "Nome",
        email: "E-mail",
        role: "Função",
        selectRole: "Selecione uma função",
        userRole: "Usuário",
        adminRole: "Administrador",
        superAdminRole: "Super Administrador",
        createUser: "Criar Usuário",
        joined: "Entrou",
        actions: "Ações",
        noUsersFound: "Nenhum usuário encontrado.",
        totalUsers: "Total de Usuários",
        // Coverage Plots
        allPlots: "Todos os Gráficos",
        myPlots: "Meus Gráficos",
        viewPlot: "Ver Gráfico",
        plotDetails: "Detalhes do Gráfico",
        userName: "Nome do Usuário",
        carriers: "Operadoras",
        coverageTypes: "Tipos de Cobertura",
        noPlotsFound: "Nenhum gráfico encontrado.",
        // System Settings Page
        currentLanguageLabel: "Idioma Atual",
        themeTab: "Tema",
        languageTab: "Idioma",
        highContrastTab: "Modo de Alto Contraste",
        brightMode: "Modo Claro",
        darkModeLabel: "Modo Escuro",
        themeDescription: "Alternar entre aparência clara e escura",
        languageDescription: "Escolha seu idioma preferido",
        highContrastDescription: "Aumente o contraste para melhor visibilidade",
        accountInfo: "Informações da Conta",
        english: "Inglês",
        spanish: "Espanhol",
        portuguese: "Português",
        french: "Francês",
        // Dashboard
        leadConversionRate: "Taxa de Conversão de Leads",
        romToProposalRate: "Taxa ROM para Proposta",
        onGoingDeals: "Negócios em Andamento",
        romsRequested: "ROMs Solicitados",
        thisYear: "Este Ano",
        lastYear: "Ano Anterior",
        last6Months: "Últimos 6 Meses",
        last3Months: "Últimos 3 Meses",
        download: "Baixar",
        latestRomRequested: "Última ROM Solicitada",
        propertyName: "Nome da Propriedade",
        areaSqFt: "Área (m²)",
        frequency: "Frequência",
        solution: "Solução",
        lastUpdate: "Última Atualização",
        status: "Status",
        localConnectivity: "Conectividade Local",
        lost: "PERDIDO",
        won: "GANHO",
        onGoing: "Em Andamento",
        romProposalsTitle: "Propostas ROM",
        searchAndViewRomProposals: "Pesquisar e ver todas as propostas ROM geradas",
        errorLoadingRomProposals: "Erro ao carregar propostas ROM",
        noRomProposalsFound: "Nenhuma proposta ROM encontrada",
        searchByVenueNameAddress: "Pesquisar por nome, endereço, tipo, fornecedor...",
        sortByVenueName: "Ordenar por Nome do Local",
        noSorting: "Sem Ordenação",
        venueNameAZ: "Nome do Local: A → Z",
        venueNameZA: "Nome do Local: Z → A",
        typeColumn: "Tipo",
        floors: "Andares",
        venueAddress: "Endereço do Local",
        totalCoverageAreaSqFt: "Área Total de Cobertura (m²)",
        parking: "Estacionamento",
        systemType: "Tipo de Sistema",
        sectors: "Setores",
        action: "Ação",
        confirmDeleteRom: "Excluir Proposta ROM?",
        confirmDeleteRomDesc: "Isso excluirá permanentemente esta proposta ROM e seus arquivos. Esta ação não pode ser desfeita.",
        deleteButton: "Excluir",
        romProposalDeleted: "Proposta ROM excluída",
        failedToDeleteRom: "Falha ao excluir proposta ROM",
        rowsPerPage: "Linhas por página",
        page: "Página",
        of: "de",
        previous: "Anterior",
        next: "Próximo",
        first: "Primeira",
        last: "Última",
        romProposalsAwaitingApproval: "Propostas ROM aguardando sua aprovação",
        pendingProposal: "Proposta Pendente",
        pendingProposals: "Propostas Pendentes",
        searchByVenueAddressCreator: "Pesquisar por local, endereço ou criador...",
        noPendingMatch: "Nenhuma proposta pendente corresponde à sua pesquisa",
        noPendingProposals: "Nenhuma proposta ROM pendente",
        allProposalsReviewed: "Todas as propostas foram revisadas",
        reject: "Rejeitar",
        approve: "Aprovar",
        approveRomProposalTitle: "Aprovar Proposta ROM?",
        rejectRomProposalTitle: "Rejeitar Proposta ROM?",
        approveRomProposalConfirm: "Tem certeza de que deseja aprovar a proposta ROM? Ela será marcada como proposta aceita.",
        rejectRomProposalConfirm: "Tem certeza de que deseja rejeitar a proposta ROM? O criador verá esta proposta como rejeitada.",
        cancel: "Cancelar",
        approved: "Aprovado",
        rejected: "Rejeitado",
        pending: "Pendente",
        proposalApprovedSuccess: "Proposta ROM aprovada com sucesso",
        proposalRejectedSuccess: "Proposta ROM rejeitada",
        approvedRoms: "ROMs Aprovados",
        allAcceptedProposals: "Todas as propostas ROM aceitas na plataforma",
        yourAcceptedProposals: "Suas propostas ROM que foram aceitas",
        searchByVenueAddressOrCreator: "Pesquisar por local, endereço ou criador...",
        searchByVenueAddressOrSystem: "Pesquisar por local, endereço ou sistema...",
        noApprovedMatch: "Nenhuma proposta aprovada corresponde à sua pesquisa",
        noApprovedProposalsYet: "Ainda não há propostas ROM aprovadas",
        errorLoadingApprovedRoms: "Erro ao carregar ROMs aprovados",
        coveragePlotsHeader: "Gráficos de Cobertura",
        viewAllCoveragePlots: "Ver todos os gráficos de cobertura de todos os usuários",
        errorLoadingPlots: "Erro ao carregar gráficos",
        coveragePlotDeleted: "Gráfico de cobertura excluído",
        failedToDeletePlot: "Falha ao excluir gráfico",
        pleaseFillMandatoryFields: "Por favor, preencha todos os campos obrigatórios.",
        mandatoryFieldsDescription: "Endereço do Local, Requisitos de Operadoras e Tipo de Cobertura são obrigatórios.",
        unknownUser: "Usuário Desconhecido",
        processQueue: "Fila de Processos",
        processQueueSubtitle: "Status atual de todos os processos de automação",
        automationQueue: "Fila de Automação",
        activeProcess: "processo ativo",
        activeProcesses: "processos ativos",
        loadingQueue: "Carregando fila...",
        noActiveProcesses: "Nenhum processo de automação ativo.",
        queueEmpty: "A fila está vazia.",
        processing: "Processando",
        running: "Em execução",
        waiting: "Aguardando...",
        waitingFilesLabel: "Arquivos em espera: ",
        searchByUsernameOrAddress: "Pesquisar por usuário ou endereço do local...",
        sortByAddress: "Ordenar por Endereço",
        addressAZ: "Endereço: A → Z",
        addressZA: "Endereço: Z → A",
    },
    fr: {
        dashboard: "Tableau de bord",
        home: "Accueil",
        romGenerator: "Générateur ROM",
        createNew: "Créer Nouveau",
        searchRom: "Rechercher ROM",
        myRoms: "Mes ROMs",
        approvals: "Approbations",
        romProposalApprovals: "Approbations des Propositions ROM",
        coveragePlot: "Tracé de Couverture",
        settings: "Paramètres",
        systemUser: "Utilisateur Système",
        systemSettings: "Paramètres Système",
        logout: "Déconnexion",
        profile: "Profil",
        welcome: "Bienvenue sur SalesHub 2.0",
        selectOption: "Sélectionnez une option dans la barre latérale pour commencer.",
        // Form Common
        back: "Retour",
        next: "Suivant",
        create: "Créer",
        createNewRom: "Créer un Nouveau ROM",
        enterVenueAddressBelow: "Entrez l'adresse du lieu ci-dessous pour commencer à créer votre ROM.",
        yes: "OUI",
        no: "NON",
        loadingMap: "Chargement de la carte...",
        osmView: "Vue OpenStreetMap",
        // Venue Info
        venueInfo: "Informations sur le lieu",
        venueName: "Nom du lieu",
        venueNamePlaceholder: "Tapez le nom du lieu",
        venueAddress: "Adresse du lieu",
        venueAddressPlaceholder: "Tapez l'adresse complète",
        venueType: "Type de lieu",
        venueTypePlaceholder: "Sélectionnez le type de lieu",
        stadium: "Stade",
        arena: "Arène",
        conventionCenter: "Centre de congrès",
        officeBuilding: "Immeuble de bureaux",
        numFloors: "Nombre d'étages",
        numFloorsPlaceholder: "Tapez le nombre total d'étages",
        grossSqFt: "Pieds carrés bruts (Total)",
        grossSqFtPlaceholder: "Tapez le total des pieds carrés bruts",
        parkingGarage: "Parking",
        parkingSqFt: "Pieds carrés du parking",
        parkingSqFtPlaceholder: "Tapez le nombre total de pieds carrés de parking",
        pops: "Populations couvertes (PoPs)",
        popsPlaceholder: "Tapez le nombre total de pops",
        thirdParty: "Tiers",
        thirdPartyName: "Nom du tiers",
        thirdPartyNamePlaceholder: "Tapez le nom du tiers",
        thirdPartyFee: "Frais du tiers (%)",
        thirdPartyFeePlaceholder: "Entrez les frais du tiers",
        ahjRequirements: "Exigences AHJ",
        buildingDensity: "Densité du bâtiment",
        densityPlaceholder: "Sélectionnez la densité",
        low: "Faible",
        medium: "Moyenne",
        high: "Élevée",
        salesManager: "Directeur des ventes",
        salesManagerPlaceholder: "Tapez le directeur des ventes/propriétaire du compte",
        expectedCloseDate: "Date de clôture prévue",
        expectedConstructionStart: "Date de début de construction prévue",
        expectedOnAirDate: "Date de mise en service prévue",
        // System Info
        systemInfo: "Informations système",
        systemType: "Type de système",
        systemTypePlaceholder: "Sélectionnez le type de système",
        dasArchitecture: "Architecture DAS",
        architecturePlaceholder: "Sélectionnez l'architecture",
        active: "Active",
        passive: "Passive",
        hybrid: "Hybride",
        oemCriteria: "Critères de sélection OEM",
        oemCriteriaPlaceholder: "Critères de sélection OEM",
        performance: "Performance",
        cost: "Coût",
        legacySupport: "Support hérité",
        dasVendor: "Fournisseur DAS",
        dasVendorPlaceholder: "Sélectionnez fournisseur DAS",
        bdaVendor: "Fournisseur BDA/Booster",
        bdaVendorPlaceholder: "Sélectionnez fournisseur BDA",
        coverageArea: "Zone de couverture ERCES",
        coverageAreaPlaceholder: "Sélectionnez la zone de couverture",
        fullBuilding: "Bâtiment complet",
        criticalAreas: "Zones critiques uniquement",
        sectorCriteria: "Critères de # de secteurs",
        sectorCriteriaPlaceholder: "Sélectionnez les critères",
        capacity: "Capacité",
        coverage: "Couverture",
        numSectors: "Nombre de secteurs",
        signalSource: "Source de signal par opérateur",
        signalSourcePlaceholder: "Sélectionnez la source de signal",
        offAir: "Off-Air",
        bts: "Station émettrice-réceptrice de base",
        smallCell: "Petite cellule",
        carrierRequirements: "Exigences de l'opérateur",
        techSupported: "Technologie prise en charge",
        additionalInfo: "Informations supplémentaires",
        additionalInfoPlaceholder: "Entrez tous les détails supplémentaires, notes ou exigences ici...",
        // Coverage Plot Form
        createCoveragePlot: "Créer un nouveau tracé de couverture",
        enterAddressBelow: "Entrez l'adresse ci-dessous pour commencer.",
        coverageTypeLabel: "Type de couverture",
        indoor: "Intérieur",
        outdoor: "Extérieur",
        indoorOutdoor: "Intérieur et Extérieur",
        success: "Succès!",
        snapshotsDownloaded: "Les instantanés du tracé de couverture pour",
        hasBeenDownloaded: "ont été téléchargés",
        creating: "Création...",
        close: "Fermer",
        createCoveragePlotButton: "Créer un Tracé de Couverture",
        venueAddressRequired: "Adresse du Lieu",
        carrierRequirementsRequired: "Exigences de l'Opérateur",
        coverageTypeRequired: "Type de Couverture",
        // User Management
        systemUsers: "Utilisateurs système",
        addUser: "Ajouter utilisateur",
        addNewUser: "Ajouter nouvel utilisateur",
        createUserDesc: "Créez un nouveau compte utilisateur. Ils recevront un e-mail pour définir leur mot de passe.",
        name: "Nom",
        email: "E-mail",
        role: "Rôle",
        selectRole: "Sélectionnez un rôle",
        userRole: "Utilisateur",
        adminRole: "Administrateur",
        superAdminRole: "Super Administrateur",
        createUser: "Créer utilisateur",
        joined: "Rejoint",
        actions: "Actions",
        noUsersFound: "Aucun utilisateur trouvé.",
        totalUsers: "Total utilisateurs",
        // Coverage Plots
        allPlots: "Tous les Tracés",
        myPlots: "Mes Tracés",
        viewPlot: "Voir le Tracé",
        plotDetails: "Détails du Tracé",
        userName: "Nom d'utilisateur",
        carriers: "Opérateurs",
        coverageTypes: "Types de Couverture",
        noPlotsFound: "Aucun tracé trouvé.",
        // System Settings Page
        currentLanguageLabel: "Langue Actuelle",
        themeTab: "Thème",
        languageTab: "Langue",
        highContrastTab: "Mode Contraste Élevé",
        brightMode: "Mode Clair",
        darkModeLabel: "Mode Sombre",
        themeDescription: "Basculer entre l'apparence claire et sombre",
        languageDescription: "Choisissez votre langue préférée",
        highContrastDescription: "Augmenter le contraste pour une meilleure visibilité",
        accountInfo: "Informations du Compte",
        english: "Anglais",
        spanish: "Espagnol",
        portuguese: "Portugais",
        french: "Français",
        // Dashboard
        leadConversionRate: "Taux de Conversion des Leads",
        romToProposalRate: "Taux ROM vers Proposition",
        onGoingDeals: "Affaires en Cours",
        romsRequested: "ROMs Demandés",
        thisYear: "Cette Année",
        lastYear: "Année Dernière",
        last6Months: "6 Derniers Mois",
        last3Months: "3 Derniers Mois",
        download: "Télécharger",
        latestRomRequested: "Dernière ROM Demandée",
        propertyName: "Nom de la Propriété",
        areaSqFt: "Surface (pieds²)",
        frequency: "Fréquence",
        solution: "Solution",
        lastUpdate: "Dernière Mise à Jour",
        status: "Statut",
        localConnectivity: "Connectivité Locale",
        lost: "PERDU",
        won: "GAGNÉ",
        onGoing: "En Cours",
        romProposalsTitle: "Propositions ROM",
        searchAndViewRomProposals: "Rechercher et voir toutes les propositions ROM générées",
        errorLoadingRomProposals: "Erreur lors du chargement des propositions ROM",
        noRomProposalsFound: "Aucune proposition ROM trouvée",
        searchByVenueNameAddress: "Rechercher par lieu, adresse, type, fournisseur...",
        sortByVenueName: "Trier par Nom du Lieu",
        noSorting: "Sans Tri",
        venueNameAZ: "Nom du Lieu: A → Z",
        venueNameZA: "Nom du Lieu: Z → A",
        typeColumn: "Type",
        floors: "Étages",
        venueAddress: "Adresse du Lieu",
        totalCoverageAreaSqFt: "Surface Totale de Couverture (pieds²)",
        parking: "Parking",
        systemType: "Type de Système",
        vendor: "Fournisseur",
        sectors: "Secteurs",
        action: "Action",
        confirmDeleteRom: "Supprimer la Proposition ROM?",
        confirmDeleteRomDesc: "Cela supprimera définitivement cette proposition ROM et ses fichiers. Cette action ne peut pas être annulée.",
        deleteButton: "Supprimer",
        romProposalDeleted: "Proposition ROM supprimée",
        failedToDeleteRom: "Échec de la suppression de la proposition ROM",
        rowsPerPage: "Lignes par page",
        page: "Page",
        of: "de",
        previous: "Précédent",
        next: "Suivant",
        first: "Première",
        last: "Dernière",
        romProposalsAwaitingApproval: "Propositions ROM en attente de votre approbation",
        pendingProposal: "Proposition en Attente",
        pendingProposals: "Propositions en Attente",
        searchByVenueAddressCreator: "Rechercher par lieu, adresse ou créateur...",
        noPendingMatch: "Aucune proposition en attente ne correspond à votre recherche",
        noPendingProposals: "Aucune proposition ROM en attente",
        allProposalsReviewed: "Toutes les propositions ont été examinées",
        reject: "Rejeter",
        approve: "Approuver",
        approveRomProposalTitle: "Approuver la Proposition ROM?",
        rejectRomProposalTitle: "Rejeter la Proposition ROM?",
        approveRomProposalConfirm: "Êtes-vous sûr de vouloir approuver la proposition ROM? Elle sera marquée comme proposition acceptée.",
        rejectRomProposalConfirm: "Êtes-vous sûr de vouloir rejeter la proposition ROM? Le créateur verra cette proposition comme rejetée.",
        cancel: "Annuler",
        approved: "Approuvé",
        rejected: "Rejeté",
        pending: "En attente",
        proposalApprovedSuccess: "Proposition ROM approuvée avec succès",
        proposalRejectedSuccess: "Proposition ROM rejetée",
        approvedRoms: "ROMs Approuvés",
        allAcceptedProposals: "Toutes les propositions ROM acceptées sur la plateforme",
        yourAcceptedProposals: "Vos propositions ROM qui ont été acceptées",
        searchByVenueAddressOrCreator: "Rechercher par lieu, adresse ou créateur...",
        searchByVenueAddressOrSystem: "Rechercher par lieu, adresse ou système...",
        noApprovedMatch: "Aucune proposition approuvée ne correspond à votre recherche",
        noApprovedProposalsYet: "Pas encore de propositions ROM approuvées",
        errorLoadingApprovedRoms: "Erreur lors du chargement des ROMs approuvés",
        coveragePlotsHeader: "Tracés de Couverture",
        viewAllCoveragePlots: "Voir tous les tracés de couverture de tous les utilisateurs",
        errorLoadingPlots: "Erreur lors du chargement des tracés",
        coveragePlotDeleted: "Tracé de couverture supprimé",
        failedToDeletePlot: "Échec de la suppression du tracé",
        pleaseFillMandatoryFields: "Veuillez remplir tous les champs obligatoires.",
        mandatoryFieldsDescription: "Adresse du Lieu, Exigences des Opérateurs et Type de Couverture sont obligatoires.",
        unknownUser: "Utilisateur Inconnu",
        processQueue: "File d'Attente des Processus",
        processQueueSubtitle: "État actuel de tous les processus d'automatisation",
        automationQueue: "File d'Automatisation",
        activeProcess: "processus actif",
        activeProcesses: "processus actifs",
        loadingQueue: "Chargement de la file...",
        noActiveProcesses: "Aucun processus d'automatisation actif.",
        queueEmpty: "La file est vide.",
        processing: "En cours",
        running: "En cours d'exécution",
        waiting: "En attente...",
        waitingFilesLabel: "Fichiers en attente : ",
        searchByUsernameOrAddress: "Rechercher par utilisateur ou adresse du lieu...",
        sortByAddress: "Trier par Adresse",
        addressAZ: "Adresse: A → Z",
        addressZA: "Adresse: Z → A",
    },
};

export function LanguageProvider({ children }) {
    const [language, setLanguage] = useState("en");

    useEffect(() => {
        const savedLanguage = localStorage.getItem("app-language");
        if (savedLanguage && translations[savedLanguage]) {
            setLanguage(savedLanguage);
        }
    }, []);

    const changeLanguage = (lang) => {
        if (translations[lang]) {
            setLanguage(lang);
            localStorage.setItem("app-language", lang);
        }
    };

    const t = (key) => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, changeLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error("useLanguage must be used within a LanguageProvider");
    }
    return context;
}
