"use client";

import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
    en: {
        dashboard: "Dashboard",
        home: "Home",
        romGenerator: "ROM Generator",
        createNew: "Create New",
        searchRom: "Search ROM",
        myRoms: "My ROM's",
        approvals: "Approvals",
        coveragePlot: "Coverage Plot",
        settings: "Settings",
        systemUser: "System User",
        systemSettings: "System Settings",
        logout: "Logout",
        profile: "Profile",
        welcome: "Welcome to SalesHub 2.0",
        selectOption: "Select an option from the sidebar to get started.",
        // Form Common
        back: "Back",
        next: "Next",
        create: "Create",
        yes: "YES",
        no: "NO",
        loadingMap: "Loading Map...",
        osmView: "OpenStreetMap View",
        // Venue Info
        venueInfo: "Venue Information",
        venueName: "Venue Name",
        venueNamePlaceholder: "Type the venue name",
        venueAddress: "Venue Address",
        venueAddressPlaceholder: "Type the venue full address",
        venueType: "Venue Type",
        venueTypePlaceholder: "Select the venue type",
        stadium: "Stadium",
        arena: "Arena",
        conventionCenter: "Convention Center",
        officeBuilding: "Office Building",
        numFloors: "Number of Floors",
        numFloorsPlaceholder: "Type the total number of floors",
        grossSqFt: "Gross sq. ft. (Total)",
        grossSqFtPlaceholder: "Type the total gross sq. ft.",
        parkingGarage: "Parking Garage",
        parkingSqFt: "Parking Garage sq. ft.",
        parkingSqFtPlaceholder: "Type the total number parking sq. ft.",
        pops: "Populations Covered (PoPs)",
        popsPlaceholder: "Type the total number of pops",
        thirdParty: "3rd Party",
        thirdPartyName: "3rd Party Name",
        thirdPartyNamePlaceholder: "Type the 3rd party name",
        thirdPartyFee: "3rd Partner Fee (%)",
        thirdPartyFeePlaceholder: "Enter the 3rd partner fee",
        ahjRequirements: "AHJ Requirements",
        buildingDensity: "Building Density",
        densityPlaceholder: "Select the density",
        low: "Low",
        medium: "Medium",
        high: "High",
        salesManager: "Sales Manager",
        salesManagerPlaceholder: "Type the sales manager/account owner",
        expectedCloseDate: "Expected Close Date",
        expectedConstructionStart: "Expected Construction Start Date",
        expectedOnAirDate: "Expected On Air Date",
        // System Info
        systemInfo: "System Information",
        systemType: "System Type",
        systemTypePlaceholder: "Select the type of the system",
        dasArchitecture: "DAS Architecture",
        architecturePlaceholder: "Select architecture",
        active: "Active",
        passive: "Passive",
        hybrid: "Hybrid",
        oemCriteria: "OEM Selection Criteria",
        oemCriteriaPlaceholder: "OEM Selection Criteria",
        performance: "Performance",
        cost: "Cost",
        legacySupport: "Legacy Support",
        dasVendor: "DAS Vendor",
        dasVendorPlaceholder: "Select DAS Vendor",
        bdaVendor: "BDA/Booster Vendor",
        bdaVendorPlaceholder: "Select BDA Vendor",
        coverageArea: "ERCES Coverage Area",
        coverageAreaPlaceholder: "Select Coverage Area",
        fullBuilding: "Full Building",
        criticalAreas: "Critical Areas Only",
        sectorCriteria: "# of Sectors Criteria",
        sectorCriteriaPlaceholder: "Select the criteria",
        capacity: "Capacity",
        coverage: "Coverage",
        numSectors: "Number of Sectors",
        signalSource: "Signal Source per Carrier",
        signalSourcePlaceholder: "Select signal source",
        offAir: "Off-Air",
        bts: "Base Transceiver Station",
        smallCell: "Small Cell",
        carrierRequirements: "Carrier Requirements",
        techSupported: "Technology Supported",
        additionalInfo: "Additional Information",
        additionalInfoPlaceholder: "Enter any additional details, notes, or requirements here...",
        // Coverage Plot Form
        createCoveragePlot: "Create New Coverage Plot",
        enterAddressBelow: "Enter the address below to start creating your new coverage plot.",
        coverageTypeLabel: "Coverage type",
        indoor: "Indoor",
        outdoor: "Outdoor",
        indoorOutdoor: "Indoor & Outdoor",
        success: "Success!",
        snapshotsDownloaded: "Snapshots of coverage plot for",
        hasBeenDownloaded: "has been downloaded",
        creating: "Creating...",
        close: "Close",
        // User Management
        systemUsers: "System Users",
        addUser: "Add User",
        addNewUser: "Add New User",
        createUserDesc: "Create a new user account. They will receive an email to set their password.",
        name: "Name",
        email: "Email",
        role: "Role",
        selectRole: "Select a role",
        userRole: "User",
        adminRole: "Admin",
        superAdminRole: "Super Admin",
        createUser: "Create User",
        joined: "Joined",
        actions: "Actions",
        noUsersFound: "No users found.",
        totalUsers: "Total Users",
        // Coverage Plots
        allPlots: "All Plots",
        myPlots: "My Plots",
        viewPlot: "View Plot",
        plotDetails: "Plot Details",
        userName: "User Name",
        carriers: "Carriers",
        coverageTypes: "Coverage Types",
        noPlotsFound: "No plots found.",
    },
    es: {
        dashboard: "Tablero",
        home: "Inicio",
        romGenerator: "Generador ROM",
        createNew: "Crear Nuevo",
        searchRom: "Buscar ROM",
        myRoms: "Mis ROMs",
        approvals: "Aprobaciones",
        coveragePlot: "Gráfico de Cobertura",
        settings: "Configuración",
        systemUser: "Usuario del Sistema",
        systemSettings: "Configuración del Sistema",
        logout: "Cerrar Sesión",
        profile: "Perfil",
        welcome: "Bienvenido a SalesHub 2.0",
        selectOption: "Seleccione una opción de la barra lateral para comenzar.",
        // Form Common
        back: "Atrás",
        next: "Siguiente",
        create: "Crear",
        yes: "SÍ",
        no: "NO",
        loadingMap: "Cargando Mapa...",
        osmView: "Vista OpenStreetMap",
        // Venue Info
        venueInfo: "Información del Lugar",
        venueName: "Nombre del Lugar",
        venueNamePlaceholder: "Escriba el nombre del lugar",
        venueAddress: "Dirección del Lugar",
        venueAddressPlaceholder: "Escriba la dirección completa",
        venueType: "Tipo de Lugar",
        venueTypePlaceholder: "Seleccione el tipo de lugar",
        stadium: "Estadio",
        arena: "Arena",
        conventionCenter: "Centro de Convenciones",
        officeBuilding: "Edificio de Oficinas",
        numFloors: "Número de Pisos",
        numFloorsPlaceholder: "Escriba el número total de pisos",
        grossSqFt: "Pies Cuadrados Brutos (Total)",
        grossSqFtPlaceholder: "Escriba el total de pies cuadrados brutos",
        parkingGarage: "Garaje de Estacionamiento",
        parkingSqFt: "Pies Cuadrados del Garaje",
        parkingSqFtPlaceholder: "Escriba el total de pies cuadrados del garaje",
        pops: "Poblaciones Cubiertas (PoPs)",
        popsPlaceholder: "Escriba el número total de pops",
        thirdParty: "Tercero",
        thirdPartyName: "Nombre del Tercero",
        thirdPartyNamePlaceholder: "Escriba el nombre del tercero",
        thirdPartyFee: "Tarifa del Tercero (%)",
        thirdPartyFeePlaceholder: "Ingrese la tarifa del tercero",
        ahjRequirements: "Requisitos AHJ",
        buildingDensity: "Densidad del Edificio",
        densityPlaceholder: "Seleccione la densidad",
        low: "Baja",
        medium: "Media",
        high: "Alta",
        salesManager: "Gerente de Ventas",
        salesManagerPlaceholder: "Escriba el gerente de ventas/propietario de la cuenta",
        expectedCloseDate: "Fecha de Cierre Esperada",
        expectedConstructionStart: "Fecha de Inicio de Construcción Esperada",
        expectedOnAirDate: "Fecha de Emisión Esperada",
        // System Info
        systemInfo: "Información del Sistema",
        systemType: "Tipo de Sistema",
        systemTypePlaceholder: "Seleccione el tipo de sistema",
        dasArchitecture: "Arquitectura DAS",
        architecturePlaceholder: "Seleccione arquitectura",
        active: "Activa",
        passive: "Pasiva",
        hybrid: "Híbrida",
        oemCriteria: "Criterios de Selección OEM",
        oemCriteriaPlaceholder: "Criterios de Selección OEM",
        performance: "Rendimiento",
        cost: "Costo",
        legacySupport: "Soporte Legado",
        dasVendor: "Proveedor DAS",
        dasVendorPlaceholder: "Seleccione Proveedor DAS",
        bdaVendor: "Proveedor BDA/Booster",
        bdaVendorPlaceholder: "Seleccione Proveedor BDA",
        coverageArea: "Área de Cobertura ERCES",
        coverageAreaPlaceholder: "Seleccione Área de Cobertura",
        fullBuilding: "Edifício Completo",
        criticalAreas: "Solo Áreas Críticas",
        sectorCriteria: "Criterios de # de Sectores",
        sectorCriteriaPlaceholder: "Seleccione los criterios",
        capacity: "Capacidad",
        coverage: "Cobertura",
        numSectors: "Número de Sectores",
        signalSource: "Fuente de Señal por Operador",
        signalSourcePlaceholder: "Seleccione fuente de señal",
        offAir: "Off-Air",
        bts: "Estación Base Transceptora",
        smallCell: "Celda Pequeña",
        carrierRequirements: "Requisitos del Operador",
        techSupported: "Tecnología Soportada",
        additionalInfo: "Información Adicional",
        additionalInfoPlaceholder: "Ingrese detalles adicionales, notas o requisitos aquí...",
        // Coverage Plot Form
        createCoveragePlot: "Crear Nuevo Gráfico de Cobertura",
        enterAddressBelow: "Ingrese la dirección a continuación para comenzar.",
        coverageTypeLabel: "Tipo de Cobertura",
        indoor: "Interior",
        outdoor: "Exterior",
        indoorOutdoor: "Interior y Exterior",
        success: "¡Éxito!",
        snapshotsDownloaded: "Las instantáneas del gráfico de cobertura para",
        hasBeenDownloaded: "se han descargado",
        creating: "Creando...",
        close: "Cerrar",
        // User Management
        systemUsers: "Usuarios del Sistema",
        addUser: "Agregar Usuario",
        addNewUser: "Agregar Nuevo Usuario",
        createUserDesc: "Crear una nueva cuenta de usuario. Recibirán un correo electrónico para establecer su contraseña.",
        name: "Nombre",
        email: "Correo Electrónico",
        role: "Rol",
        selectRole: "Seleccionar un rol",
        userRole: "Usuario",
        adminRole: "Administrador",
        superAdminRole: "Super Administrador",
        createUser: "Crear Usuario",
        joined: "Unido",
        actions: "Acciones",
        noUsersFound: "No se encontraron usuarios.",
        totalUsers: "Usuarios Totales",
        // Coverage Plots
        allPlots: "Todos los Gráficos",
        myPlots: "Mis Gráficos",
        viewPlot: "Ver Gráfico",
        plotDetails: "Detalles del Gráfico",
        userName: "Nombre de Usuario",
        carriers: "Operadores",
        coverageTypes: "Tipos de Cobertura",
        noPlotsFound: "No se encontraron gráficos.",
    },
    pt: {
        dashboard: "Painel",
        home: "Início",
        romGenerator: "Gerador ROM",
        createNew: "Criar Novo",
        searchRom: "Buscar ROM",
        myRoms: "Meus ROMs",
        approvals: "Aprovações",
        coveragePlot: "Gráfico de Cobertura",
        settings: "Configurações",
        systemUser: "Usuário do Sistema",
        systemSettings: "Configurações do Sistema",
        logout: "Sair",
        profile: "Perfil",
        welcome: "Bem-vindo ao SalesHub 2.0",
        selectOption: "Selecione uma opção na barra lateral para começar.",
        // Form Common
        back: "Voltar",
        next: "Próximo",
        create: "Criar",
        yes: "SIM",
        no: "NÃO",
        loadingMap: "Carregando Mapa...",
        osmView: "Visualização OpenStreetMap",
        // Venue Info
        venueInfo: "Informações do Local",
        venueName: "Nome do Local",
        venueNamePlaceholder: "Digite o nome do local",
        venueAddress: "Endereço do Local",
        venueAddressPlaceholder: "Digite o endereço completo",
        venueType: "Tipo de Local",
        venueTypePlaceholder: "Selecione o tipo de local",
        stadium: "Estádio",
        arena: "Arena",
        conventionCenter: "Centro de Convenções",
        officeBuilding: "Edifício de Escritórios",
        numFloors: "Número de Andares",
        numFloorsPlaceholder: "Digite o número total de andares",
        grossSqFt: "Área Bruta (Total)",
        grossSqFtPlaceholder: "Digite o total da área bruta",
        parkingGarage: "Garagem",
        parkingSqFt: "Área da Garagem",
        parkingSqFtPlaceholder: "Digite a área total da garagem",
        pops: "Populações Cobertas (PoPs)",
        popsPlaceholder: "Digite o número total de pops",
        thirdParty: "Terceiros",
        thirdPartyName: "Nome do Terceiro",
        thirdPartyNamePlaceholder: "Digite o nome do terceiro",
        thirdPartyFee: "Taxa do Terceiro (%)",
        thirdPartyFeePlaceholder: "Insira a taxa do terceiro",
        ahjRequirements: "Requisitos AHJ",
        buildingDensity: "Densidade do Edifício",
        densityPlaceholder: "Selecione a densidade",
        low: "Baixa",
        medium: "Média",
        high: "Alta",
        salesManager: "Gerente de Vendas",
        salesManagerPlaceholder: "Digite o gerente de vendas/proprietário da conta",
        expectedCloseDate: "Data Prevista de Fechamento",
        expectedConstructionStart: "Data Prevista de Início da Construção",
        expectedOnAirDate: "Data Prevista de Entrada no Ar",
        // System Info
        systemInfo: "Informações do Sistema",
        systemType: "Tipo de Sistema",
        systemTypePlaceholder: "Selecione o tipo de sistema",
        dasArchitecture: "Arquitetura DAS",
        architecturePlaceholder: "Selecione a arquitetura",
        active: "Ativa",
        passive: "Passiva",
        hybrid: "Híbrida",
        oemCriteria: "Critérios de Seleção OEM",
        oemCriteriaPlaceholder: "Critérios de Seleção OEM",
        performance: "Desempenho",
        cost: "Custo",
        legacySupport: "Suporte Legado",
        dasVendor: "Fornecedor DAS",
        dasVendorPlaceholder: "Selecione Fornecedor DAS",
        bdaVendor: "Fornecedor BDA/Booster",
        bdaVendorPlaceholder: "Selecione Fornecedor BDA",
        coverageArea: "Área de Cobertura ERCES",
        coverageAreaPlaceholder: "Selecione Área de Cobertura",
        fullBuilding: "Edifício Completo",
        criticalAreas: "Apenas Áreas Críticas",
        sectorCriteria: "Critérios de # de Setores",
        sectorCriteriaPlaceholder: "Selecione os critérios",
        capacity: "Capacidade",
        coverage: "Cobertura",
        numSectors: "Número de Setores",
        signalSource: "Fonte de Sinal por Operadora",
        signalSourcePlaceholder: "Selecione fonte de sinal",
        offAir: "Off-Air",
        bts: "Estação Transceptora Base",
        smallCell: "Small Cell",
        carrierRequirements: "Requisitos da Operadora",
        techSupported: "Tecnologia Suportada",
        additionalInfo: "Informações Adicionais",
        additionalInfoPlaceholder: "Insira detalhes adicionais, notas ou requisitos aqui...",
        // Coverage Plot Form
        createCoveragePlot: "Criar Novo Gráfico de Cobertura",
        enterAddressBelow: "Insira o endereço abaixo para começar.",
        coverageTypeLabel: "Tipo de Cobertura",
        indoor: "Interior",
        outdoor: "Exterior",
        indoorOutdoor: "Interior e Exterior",
        success: "Sucesso!",
        snapshotsDownloaded: "Instantâneos do gráfico de cobertura para",
        hasBeenDownloaded: "foram baixados",
        creating: "Criando...",
        close: "Fechar",
        // User Management
        systemUsers: "Usuários do Sistema",
        addUser: "Adicionar Usuário",
        addNewUser: "Adicionar Novo Usuário",
        createUserDesc: "Crie uma nova conta de usuário. Eles receberão um e-mail para definir a senha.",
        name: "Nome",
        email: "E-mail",
        role: "Função",
        selectRole: "Selecione uma função",
        userRole: "Usuário",
        adminRole: "Administrador",
        superAdminRole: "Super Administrador",
        createUser: "Criar Usuário",
        joined: "Entrou",
        actions: "Ações",
        noUsersFound: "Nenhum usuário encontrado.",
        totalUsers: "Total de Usuários",
        // Coverage Plots
        allPlots: "Todos os Gráficos",
        myPlots: "Meus Gráficos",
        viewPlot: "Ver Gráfico",
        plotDetails: "Detalhes do Gráfico",
        userName: "Nome do Usuário",
        carriers: "Operadoras",
        coverageTypes: "Tipos de Cobertura",
        noPlotsFound: "Nenhum gráfico encontrado.",
    },
    fr: {
        dashboard: "Tableau de bord",
        home: "Accueil",
        romGenerator: "Générateur ROM",
        createNew: "Créer Nouveau",
        searchRom: "Rechercher ROM",
        myRoms: "Mes ROMs",
        approvals: "Approbations",
        coveragePlot: "Tracé de Couverture",
        settings: "Paramètres",
        systemUser: "Utilisateur Système",
        systemSettings: "Paramètres Système",
        logout: "Déconnexion",
        profile: "Profil",
        welcome: "Bienvenue sur SalesHub 2.0",
        selectOption: "Sélectionnez une option dans la barre latérale pour commencer.",
        // Form Common
        back: "Retour",
        next: "Suivant",
        create: "Créer",
        yes: "OUI",
        no: "NON",
        loadingMap: "Chargement de la carte...",
        osmView: "Vue OpenStreetMap",
        // Venue Info
        venueInfo: "Informations sur le lieu",
        venueName: "Nom du lieu",
        venueNamePlaceholder: "Tapez le nom du lieu",
        venueAddress: "Adresse du lieu",
        venueAddressPlaceholder: "Tapez l'adresse complète",
        venueType: "Type de lieu",
        venueTypePlaceholder: "Sélectionnez le type de lieu",
        stadium: "Stade",
        arena: "Arène",
        conventionCenter: "Centre de congrès",
        officeBuilding: "Immeuble de bureaux",
        numFloors: "Nombre d'étages",
        numFloorsPlaceholder: "Tapez le nombre total d'étages",
        grossSqFt: "Pieds carrés bruts (Total)",
        grossSqFtPlaceholder: "Tapez le total des pieds carrés bruts",
        parkingGarage: "Parking",
        parkingSqFt: "Pieds carrés du parking",
        parkingSqFtPlaceholder: "Tapez le nombre total de pieds carrés de parking",
        pops: "Populations couvertes (PoPs)",
        popsPlaceholder: "Tapez le nombre total de pops",
        thirdParty: "Tiers",
        thirdPartyName: "Nom du tiers",
        thirdPartyNamePlaceholder: "Tapez le nom du tiers",
        thirdPartyFee: "Frais du tiers (%)",
        thirdPartyFeePlaceholder: "Entrez les frais du tiers",
        ahjRequirements: "Exigences AHJ",
        buildingDensity: "Densité du bâtiment",
        densityPlaceholder: "Sélectionnez la densité",
        low: "Faible",
        medium: "Moyenne",
        high: "Élevée",
        salesManager: "Directeur des ventes",
        salesManagerPlaceholder: "Tapez le directeur des ventes/propriétaire du compte",
        expectedCloseDate: "Date de clôture prévue",
        expectedConstructionStart: "Date de début de construction prévue",
        expectedOnAirDate: "Date de mise en service prévue",
        // System Info
        systemInfo: "Informations système",
        systemType: "Type de système",
        systemTypePlaceholder: "Sélectionnez le type de système",
        dasArchitecture: "Architecture DAS",
        architecturePlaceholder: "Sélectionnez l'architecture",
        active: "Active",
        passive: "Passive",
        hybrid: "Hybride",
        oemCriteria: "Critères de sélection OEM",
        oemCriteriaPlaceholder: "Critères de sélection OEM",
        performance: "Performance",
        cost: "Coût",
        legacySupport: "Support hérité",
        dasVendor: "Fournisseur DAS",
        dasVendorPlaceholder: "Sélectionnez fournisseur DAS",
        bdaVendor: "Fournisseur BDA/Booster",
        bdaVendorPlaceholder: "Sélectionnez fournisseur BDA",
        coverageArea: "Zone de couverture ERCES",
        coverageAreaPlaceholder: "Sélectionnez la zone de couverture",
        fullBuilding: "Bâtiment complet",
        criticalAreas: "Zones critiques uniquement",
        sectorCriteria: "Critères de # de secteurs",
        sectorCriteriaPlaceholder: "Sélectionnez les critères",
        capacity: "Capacité",
        coverage: "Couverture",
        numSectors: "Nombre de secteurs",
        signalSource: "Source de signal par opérateur",
        signalSourcePlaceholder: "Sélectionnez la source de signal",
        offAir: "Off-Air",
        bts: "Station émettrice-réceptrice de base",
        smallCell: "Petite cellule",
        carrierRequirements: "Exigences de l'opérateur",
        techSupported: "Technologie prise en charge",
        additionalInfo: "Informations supplémentaires",
        additionalInfoPlaceholder: "Entrez tous les détails supplémentaires, notes ou exigences ici...",
        // Coverage Plot Form
        createCoveragePlot: "Créer un nouveau tracé de couverture",
        enterAddressBelow: "Entrez l'adresse ci-dessous pour commencer.",
        coverageTypeLabel: "Type de couverture",
        indoor: "Intérieur",
        outdoor: "Extérieur",
        indoorOutdoor: "Intérieur et Extérieur",
        success: "Succès!",
        snapshotsDownloaded: "Les instantanés du tracé de couverture pour",
        hasBeenDownloaded: "ont été téléchargés",
        creating: "Création...",
        close: "Fermer",
        // User Management
        systemUsers: "Utilisateurs système",
        addUser: "Ajouter utilisateur",
        addNewUser: "Ajouter nouvel utilisateur",
        createUserDesc: "Créez un nouveau compte utilisateur. Ils recevront un e-mail pour définir leur mot de passe.",
        name: "Nom",
        email: "E-mail",
        role: "Rôle",
        selectRole: "Sélectionnez un rôle",
        userRole: "Utilisateur",
        adminRole: "Administrateur",
        superAdminRole: "Super Administrateur",
        createUser: "Créer utilisateur",
        joined: "Rejoint",
        actions: "Actions",
        noUsersFound: "Aucun utilisateur trouvé.",
        totalUsers: "Total utilisateurs",
        // Coverage Plots
        allPlots: "Tous les Tracés",
        myPlots: "Mes Tracés",
        viewPlot: "Voir le Tracé",
        plotDetails: "Détails du Tracé",
        userName: "Nom d'utilisateur",
        carriers: "Opérateurs",
        coverageTypes: "Types de Couverture",
        noPlotsFound: "Aucun tracé trouvé.",
    },
};

export function LanguageProvider({ children }) {
    const [language, setLanguage] = useState("en");

    useEffect(() => {
        const savedLanguage = localStorage.getItem("app-language");
        if (savedLanguage && translations[savedLanguage]) {
            setLanguage(savedLanguage);
        }
    }, []);

    const changeLanguage = (lang) => {
        if (translations[lang]) {
            setLanguage(lang);
            localStorage.setItem("app-language", lang);
        }
    };

    const t = (key) => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, changeLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error("useLanguage must be used within a LanguageProvider");
    }
    return context;
}
