import "./globals.css";
import { AuthProvider } from "@/components/providers/auth-provider";

import { Toaster } from "@/components/ui/sonner";

export const metadata = {
  title: "SalesHub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        <AuthProvider>
          {children}
        </AuthProvider>
        <Toaster position="bottom-right" />
      </body>
    </html>
  );
}
